---
- hosts: localhost
  connection: true
  tasks:
  - name: Create EC2 instances with Ubuntu and Debian
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "windows-demo"
      instance_type: t3.micro
      security_group: launch-wizard-2
      region: eu-north-1
      aws_access_key: "{{ ec2_aceess_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - { image: "ami-09a9858973b288bdd", name: "ubuntu-instance1"}
      - { image: "ami-09a9858973b288bdd", name: "ubuntu-instance2"}
      - { image: "ami-01427dce5d2537266", name: "debian-instance"}
